# Generated by Django 4.1.4 on 2022-12-29 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='contact',
            new_name='phone',
        ),
    ]
