# Generated by Django 4.1.4 on 2022-12-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_contact_register_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='forgot_password_token',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
