# Generated by Django 4.1.4 on 2022-12-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_register_forgot_password_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='forgot_password_token',
            field=models.CharField(max_length=100),
        ),
    ]
