# Generated by Django 4.1.4 on 2022-12-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_register_forgot_password_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='forgot_password_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
