# Generated by Django 4.1.4 on 2023-01-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_register_forgot_password_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='standalone',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=20),
        ),
    ]
